### ISSUE TITLE
Using it with Karma

### ISSUE THREAD

**Issue by bySabi** [STRML/babel-plugin-es2015-maybe-webpack#2]
Hi @STRML.
I create a npm package that add the needed boilerplate for test React projects using Karma, Tape and Webpack, [carma-tap-webpack](https://github.com/bySabi/carma-tap-webpack). It is very parametizable and I use sucessful on [React Scrollaware](https://github.com/bySabi/react-scrollaware)
Now I`m in the process of add istambuljs coverage too. The plan is use [babel-plugin-istanbul](https://github.com/istanbuljs/babel-plugin-istanbul) together with webpack in karma. 
I want extend target projects .babelrc with, for Ex: 

```
"env": {
    "test": {
      "plugins": [ "istanbul" ]
    }
  }
```

from `karma.conf.js` using webpack settings.
Until to day, your are the only person that make a subject about. I don´t know yet how I can use `babel-plugin-es2015-maybe-webpack` or what ever ...
Maybe I have to use/create a .babelrc parser for webpack ?
Any advice ??

**Comment by STRML** [comment]
You can parse .babelrc easily with https://www.npmjs.com/package/json5.
